### ISSUE TITLE
Getting an Error Loop Message when i start AutoTouch on iOS 14.

### ISSUE THREAD

**Issue by Chibyqt** [kentkrantz/AutoTouchIssues#9]
Jailbreaked it with Odyseera1n and installed newest version - when i start AutoTouch i get this Error Message and i cant click it away because its coming over and over again.

![image](https://user-images.githubusercontent.com/71782872/94328264-46c79280-ffb1-11ea-92b3-61ca24eee692.png)

guess its a ios 14 problem because RocketBootstrap got updated by Coolstar for ios 14.

**Comment by sideloading** [comment]
@Chibyqt Can you install RocketBootstrap v1.0.10 beta 1 or later from the following repo https://rpetri.ch/repo/? It fixed this problem for me, but I used checkra1n.

**Comment by Chibyqt** [comment]
> @Chibyqt Can you install RocketBootstrap v1.0.10 beta 1 or later from the following repo https://rpetri.ch/repo/? It fixed this problem for me, but I used checkra1n.

thx - worked! Didnt noticed that Rocketbootstrap got "official" updated for iOS 14 =) <3

**Comment by sideloading** [comment]
@Chibyqt No problem. Feel free to close the issue.
